### ISSUE TITLE
Semicolon text read by TTS

### ISSUE THREAD

**Issue by izaxon** [izaxon/voice365#2]
Milan: "There is however still a problem with the titles of all main sections. There is no pause in the voice after the title, and the voice always read ‘semicolon, semicolon’ at the end of the title (semicolon is the word for this character ‘;’).

I’ve also found a problem with the number ‘1.’, both before the first title and also in the list at the beginning of the the pkv. The voice say ‘til en’ instead of ‘en’ (in English: ‘to one’ instead of ‘one’). I don’t know where ‘til’ (‘to’) comes from."

**Comment by izaxon** [comment]
Text is formatted like this (for the TTS):
`Innledning.;;PAKNINGSVEDLEGG: INFORMASJON TIL BRUKEREN Canoderm Krem 5 % karbamid (ureum) Les nøye gjennom dette pakningsvedlegget. Det inneholder informasjon som er viktig for deg. Dette legemidlet er reseptfritt. Likevel må Canoderm brukes med forsiktighet for å oppnå best mulig resultat. Ta vare på dette pakningsvedlegget. Du kan få behov for å lese det igjen. Spør på apoteket dersom du trenger mer informasjon eller råd. Du må kontakte lege dersom symptomene dine forverres eller ikke bedres. Kontakt lege eller apotek dersom noen av bivirkningene blir plagsomme eller du merker bivirkninger som ikke er nevnt i dette pakningsvedlegget. I dette pakningsvedlegget finner du informasjon om: 1. Hva Canoderm er, og hva det brukes mot 2. Hva du må ta hensyn til før du bruker Canoderm 3. Hvordan du bruker Canoderm 4. Mulige bivirkninger 5. Hvordan du oppbevarer Canoderm 6. Ytterligere informasjon.`

**Comment by gyalai** [comment]
That means after every title you add two semicolons? Do you know why is that the case? How long that is like that?

**Comment by izaxon** [comment]
It is to add an additional pause (I guess). It has been so historically (in initial implementation).

**Comment by izaxon** [comment]
I cannot repeat the bug. Can you please get back with id of a job?

My test:
https://voice365-felleskatalogen.azurewebsites.net/api/GetFileInfo?code=XkWWOhY9YAFHvjDoyzlSVs8FR/nzdMpvNNo5OaZS1VtJQdu9YOIapQ==&p=067923&a=1

**Comment by gyalai** [comment]
this is one of the job id: 4efa853c-85de-451e-bb7f-6ba7e2714930 .

You can check here:
https://www.felleskatalogen.no/medisin/pasienter/pil-abasaglar-lilly-611872

But I think it is bad in the chapters no in the heading.

**Comment by izaxon** [comment]
Avsnitt text:
`1: Hva ABASAGLAR er og hva det brukes mot;;ABASAGLAR er en injeksjonsvæske som inneholder insulin glargin. Insulin glargin er et modifisert insulin, meget likt humaninsulin (det insulin kroppen produserer). ABASAGLAR anvendes for å behandle diabetes mellitus (sukkersyke) hos voksne, ungdom og barn fra 2 års alder. Ved diabetes mellitus produserer ikke kroppen tilstrekkelig insulin til å kunne holde blodsukkeret under kontroll. Insulin glargin har langvarig og stabil blodsukkersenkende effekt.`

**Comment by gyalai** [comment]
This is what I sending.


`<Avsnitt AvsnittNr="2">
            <Tittel>1: Hva ABASAGLAR er og hva det brukes mot</Tittel>
            <Beskrivelse>ABASAGLAR er en injeksjonsvæske som inneholder insulin glargin. Insulin
                glargin er et modifisert insulin, meget likt humaninsulin (det insulin kroppen
                produserer). ABASAGLAR anvendes for å behandle diabetes mellitus (sukkersyke) hos
                voksne, ungdom og barn fra 2 års alder. Ved diabetes mellitus produserer ikke
                kroppen tilstrekkelig insulin til å kunne holde blodsukkeret under kontroll. Insulin
                glargin har langvarig og stabil blodsukkersenkende effekt.</Beskrivelse>
        </Avsnitt>`

**Comment by izaxon** [comment]
I can confirm that:
- text;; => speaks "semicolon" (this is due to the updated Acapela TTS)
- 1: => speaks "till en" (this is due to a faulty(?) lexicon entry)

**Comment by izaxon** [comment]
- [x] Update producer to set .;; instead of ;;
- [x] Remove lexicon entry

**Comment by gyalai** [comment]
great that you find the issue. I'm reporting it to Bente. What do you think when you can fix this?

**Comment by izaxon** [comment]
Fixed. Please run test to confirm.

**Comment by gyalai** [comment]
okay sending

**Comment by gyalai** [comment]
It is still not produced any voice file. Could you check?

**Comment by izaxon** [comment]
Producing...

**Comment by gyalai** [comment]
now I see :)

**Comment by gyalai** [comment]
It seems good to me. I'm asking Bente to test it too.

**Comment by gyalai** [comment]
Bente said the new voice is fine. I'm going to regenerate all of the PKV-s

**Comment by gyalai** [comment]
Hi, The ‘til en’ (‘to one’) is still present in the newly generated files.

**Comment by izaxon** [comment]
Hi, can you provide id of a job or pakno for a newly generated file?

**Comment by gyalai** [comment]
Bente said it is in all of the newly generated voices. We regenerated all of them on Tuesday.

**Comment by izaxon** [comment]
@gyalai Can you please re-produce one job now. Then I will check that it is ok and that the log files are correct.

**Comment by izaxon** [comment]
The lexicon manager loaded the old lexicon and the new at the same time. So the old transcription was still there.
