### ISSUE TITLE
voice365storage.queue.core.windows.net link is not working

### ISSUE THREAD

**Issue by gyalai** [izaxon/voice365#5]
Hi,

The voice365storage.queue.core.windows.net link is not working for a while. Please check what is going on. 

BR,
Milan

**Comment by izaxon** [comment]
For access to the all services (blob, queues)?
Or for a specific queue (e.g. fkxml)?

**Comment by gyalai** [comment]
For the queues at least. We can not fetch the fkstate queue and we can not send message to the fkxml queue.

**Comment by izaxon** [comment]
Ok. I will generate new links.

**Comment by izaxon** [comment]
Links generated and emailed to you. Please confirm that the work.

**Comment by gyalai** [comment]
Hi,

The links seems okay but  something is not good with the permissions.

We get this error "This request is not authorized to perform this operation using this permission"


Is there a way to give us permanent links not this 1 year ones?

BR,
Milan

**Comment by izaxon** [comment]
Hi, when do you get the error? That is what operation are you trying to do on the queue?

We can make them longer than 1 year, e.g. 5 or 10 years.

**Comment by gyalai** [comment]
when I'm trying to read the fkstate queue or add element to the fkxml

**Comment by izaxon** [comment]
?sv=2016-05-31&ss=q&srt=sco&sp=rwacup&se=2027-05-18T20:01:48Z&st=2017-05-18T12:01:48Z&spr=https&sig=%2Fe%2FA7SGPN4lzx4Y8JsG%2FOwrWENvbzYjpDntF0IY%2FSUU%3D

**Comment by izaxon** [comment]
Try with this

**Comment by gyalai** [comment]
For which queue?

**Comment by izaxon** [comment]
Both

**Comment by gyalai** [comment]
we get the same error still, Isn't there any log in the azure to figure out why it is not able to connect?

**Comment by gyalai** [comment]
It is still not working for me. Have you been able to test?

**Comment by izaxon** [comment]
Yes. I have tried with old unit test using the old SAS. It works. Can you share the code you use to access the fkxml queue?

**Comment by gyalai** [comment]
This it he error when we are fetching the fkstate:

`Caused by: java.net.UnknownHostException: voice365storage.queue.core.windows.net`

It doesn't said to much. The error code what we got back is 500. But sometimes the fetch works but noe messages arrives for your side.


I'm investigating about the post part.

**Comment by izaxon** [comment]
I see that there is not a 100% success rate in calls to the storage account.
I have opened a service request with Azure support and I am now running the logger in real-time for the API functions.

**Comment by gyalai** [comment]
sounds good
I find an issue on or side with my current daily test ,so now I'm able to send messages to you

**Comment by gyalai** [comment]
Couldn't be a request limit for the account? We are making 1r/s

**Comment by izaxon** [comment]
What was the issue? I.e. how could that lead to errors from Azure?

**Comment by gyalai** [comment]
The issue was I wasn't been able to post you a request because the voice files wasn't available in my server :). It is not connected to the 500 error code.

**Comment by gyalai** [comment]
Could you check that you got generation requests? I sent you 3 in the last 5 min. Nothing came back so far.

**Comment by izaxon** [comment]
I can see the requests...files are being produced right now.

**Comment by gyalai** [comment]
great. If the system is working then I will start a bulk generation if it is okay with you

**Comment by gyalai** [comment]
Can you notify  me if any of the job has been finished on your side?

**Comment by izaxon** [comment]
What was the id of the jobs?

**Comment by gyalai** [comment]
The fkids were 10302432, 10302314, 10303122 . Is it enough?

**Comment by izaxon** [comment]
Have you called GetJobInfo to check on the jobs? (the easiest ;-)

**Comment by gyalai** [comment]
No, I haven't but it doesn't matter if I don't get the message on the message queue. :D

**Comment by izaxon** [comment]
fkids not searchable, do you have job ids?

**Comment by gyalai** [comment]
These are the ids:
56500164-6bc0-45f0-b494-f249a17bf548, 7325c499-00f3-4217-b55e-3cea927fdafc, ce4da919-de8e-48e5-ad3b-4057a3f629c1

**Comment by gyalai** [comment]
The GetJobInfo returns with 404

**Comment by gyalai** [comment]
Can I help you with something?

**Comment by izaxon** [comment]
https://voice365-felleskatalogen.azurewebsites.net/api/GetJobInfo?code=0s2K2gwBpi9yg8eX4RLxt0NKMWr/luxr66C/fVr2d4/lpVOu1zeHaA==&id=ce4da919-de8e-48e5-ad3b-4057a3f629c1

**Comment by gyalai** [comment]
It's 404 for me. What should I see there?

**Comment by izaxon** [comment]
It says the job was not found...will check the database...

**Comment by izaxon** [comment]
I cannot find id ce4da919-de8e-48e5-ad3b-4057a3f629c1 in the database.

**Comment by gyalai** [comment]
what id have you find? You said you saw that something has been process. Than what was that's id?

**Comment by izaxon** [comment]
I cannot (easily) search old log items at the moment. Can you please send a new job, a single one and provide me with the id of it? I will watch the logs...

**Comment by izaxon** [comment]
...the only job received in the past 4 hours is with id: e7543dcf-caba-4745-85df-71217bff2c6a

**Comment by gyalai** [comment]
I sent one just right now with id: 2a65fc18-8bad-4c6c-9c11-cc560c78834a

**Comment by gyalai** [comment]
Can we speed up this debugging tomorrow or after that?

**Comment by izaxon** [comment]
Yep.
What I have detected so far:
1. some files do not seem to be uploaded (jobs with e.g. id ae02486d-bc18-4e9e-a4fd-bb7d8b0fc5f5, e7543dcf-caba-4745-85df-71217bff2c6a) => it looks like upload of the files to blob storage was not performed before the job (with id) was sent to the server
2. start of job using the following code works fine (it produces):
```
        public async Task TestMethod_PostXmlQueueUsingSAS()
        {
            string sasUri = "https://voice365storage.queue.core.windows.net:443/fkxml?st=2017-02-28T13%3A23%3A00Z&se=2027-03-01T13%3A23%3A00Z&sp=a&sv=2015-12-11&sig=XXXXXX";
            var queue = new CloudQueue(new Uri(sasUri));
            var json = "{ \"id\":\"589817\",\"jobTimeStamp\":1487323956599,\"timestamp\":1487323957742,\"fkid\":\"10303118\",\"purpose\":\"PUBLISH\",\"fileId\":\"2433\",\"step\":\"XML_FILE_UPLOADED\",\"errorId\":0,\"text\":null}";
            await queue.AddMessageAsync(new CloudQueueMessage(json));
        }
```
3. upload to blob storage works as well:
```
 var id = "589817";
            string sasUri = $"https://voice365storage.blob.core.windows.net/fkxml/{id}?st=2017-02-26T12%3A35%3A00Z&se=2027-02-27T12%3A35%3A00Z&sp=w&sv=2015-12-11&sr=c&sig=XXXXXX";

            var blob = new CloudBlockBlob(new Uri(sasUri));

            using (var fs = File.OpenRead("data\\589817.xml"))
            {
                await blob.UploadFromStreamAsync(fs);
            }

            Console.WriteLine("Create operation succeeded for SAS {0}", sasUri);
            Console.WriteLine();
```

**Comment by izaxon** [comment]
Questions:
1. Do you upload to the correct location?
2. Do you queue messages to the right locations?

My observations is that old SAS works (see 2 and 3 above) and that the producer cannot download some files.

**Comment by izaxon** [comment]
FYI - snapshot of logger for uploaded jobs (to queue fkxml):
![image](https://cloud.githubusercontent.com/assets/805898/26324512/577566ee-3f33-11e7-8767-e2846236e496.png)

**Comment by gyalai** [comment]
When we could start the Skype talk?

**Comment by izaxon** [comment]
Now

**Comment by izaxon** [comment]
Access url to blob storage: voice365storage.blob.core.windows.net/fkxml (could also be voice365storage.blobs.core.windows.net/fkxml).

**Comment by gyalai** [comment]
Are you sure you sending message back when the audio file is ready? NO messages arrives for the message queue with that message.

**Comment by gyalai** [comment]
never mind

**Comment by gyalai** [comment]
I found the issues on our side. The message queue reach fail sometime because a bug in our DNS server and therefore it can not reach the queue neither the store.

Because of this exception the messaging processing stopped right after the first issue. I'm fixing these and will come back to you if everything is fine

**Comment by gyalai** [comment]
It seems to work now. I'm starting a bulk generation
